public class Exercicio_12 {
    
    public static String Escreve_Por_Extenso_1_a_99(int valor){
        String devolucao;
        switch(valor){
            case 1: devolucao = "UM";
            break;
            case 2: devolucao = "DOIS";
            break;
            case 3: devolucao = "TRES";
            break;
            case 4: devolucao = "QUATRO";
            break;
            case 5: devolucao = "CINCO";
            break;
            case 6: devolucao = "SEIS";
            break;
            case 7: devolucao = "SETE";
            break;
            case 8: devolucao = "OITO";
            break;
            case 9: devolucao = "NOVE";
            break;
            case 10: devolucao = "DEZ";
            break;
            case 11: devolucao = "ONZE";
            break;
            case 12: devolucao = "DOZE";
            break;
            case 13: devolucao = "TREZE";
            break;
            case 14: devolucao = "QUATORZE";
            break;
            case 15: devolucao = "QUINZE";
            break;
            case 16: devolucao = "DEZESSEIS";
            break;
            case 17: devolucao = "DEZESSETE";
            break;
            case 18: devolucao = "DEZOITO";
            break;
            case 19: devolucao = "DEZENOVE";
            break;
            case 20: devolucao = "VINTE";
            break;
            case 21: devolucao = "VINTE E UM";
            break;
            case 22: devolucao = " VINTE E DOIS";
            break;
            case 23: devolucao = "VINTE E TRES";
            break;
            case 24: devolucao = "VINTE E QUATRO";
            break;
            case 25: devolucao = "VINTE E CINCO";
            break;
            case 26: devolucao = "VINTE E SEIS";
            break;
            case 27: devolucao = "VINTE E SETE";
            break;
            case 28: devolucao = "VINTE E OITO";
            break;
            case 29: devolucao = "VINTE E NOVE";
            break;
            case 30: devolucao = "TRINTA";
            break;
            case 31: devolucao = "TRINTA E UM";
            break;
            case 32: devolucao = "TRINTA E DOIS";
            break;
            case 33: devolucao = "TRINTA E TRES";
            break;
            case 34: devolucao = "TRINTA E QUATRO";
            break;
            case 35: devolucao = "TRINTA E CINCO";
            break;
            case 36: devolucao = "TRINTA E SEIS";
            break;
            case 37: devolucao = "TRINTA E SETE";
            break;
            case 38: devolucao = "TRINTA E OITO";
            break;
            case 39: devolucao = "TRINTA E NOVE";
            break;
            case 40: devolucao = "QUARENTA";
            break;
            case 41: devolucao = "QUARENTA E UM";
            break;
            case 42: devolucao = "QUARENTA E DOIS";
            break;
            case 43: devolucao = "QUARENTA E TRES";
            break;
            case 44: devolucao = "QUARENTA E QUATRO";
            break;
            case 45: devolucao = "QUARENTA E CINCO";
            break;
            case 46: devolucao = "QUARENTA E SEIS";
            break;
            case 47: devolucao = "QUARENTA E SETE";
            break;
            case 48: devolucao = "QUARENTA E OITO";
            break;
            case 49: devolucao = "QUARENTA E NOVE";
            break;
            case 50: devolucao = "CINQUENTA";
            break;
            case 51: devolucao = "CINQUENTA E UM";
            break;
            case 52: devolucao = "CINQUENTA E DOIS";
            break;
            case 53: devolucao = "CINQUENTA E TRES";
            break;
            case 54: devolucao = "CINQUENTA E QUATRO";
            break;
            case 55: devolucao = "CINQUENTA E CINCO";
            break;
            case 56: devolucao = "CINQUENTA E SEIS";
            break;
            case 57: devolucao = "CINQUENTA E SETE";
            break;
            case 58: devolucao = "CINQUENTA E OITO";
            break;
            case 59: devolucao = "CINQUENTA E NOVE";
            break;
            case 60: devolucao = "SESSENTA";
            break;
            case 61: devolucao = "SESSENTA E UM";
            break;
            case 62: devolucao = "SESSENTA E DOIS";
            break;
            case 63: devolucao = "SESSENTA E TRES";
            break;
            case 64: devolucao = "SESSENTA E QUATRO";
            break;
            case 65: devolucao = "SESSENTA E CINCO";
            break;
            case 66: devolucao = "SESSENTA E SEIS";
            break;
            case 67: devolucao = "SESSENTA E SETE";
            break;
            case 68: devolucao = "SESSENTA E OITO";
            break;
            case 69: devolucao = "SESSENTA E NOVE";
            break;
            case 70: devolucao = "SETENTA";
            break;
            case 71: devolucao = "SETENTA E UM";
            break;
            case 72: devolucao = "SETENTA E DOIS";
            break;
            case 73: devolucao = "SETENTA E TRES";
            break;
            case 74: devolucao = "SETENTA E QUATRO";
            break;
            case 75: devolucao = "SETENTA E CINCO";
            break;
            case 76: devolucao = "SETENTA E SEIS";
            break;
            case 77: devolucao = "SETENTA E SETE";
            break;
            case 78: devolucao = "SETENTA E OITO";
            break;
            case 79: devolucao = "SETENTA E NOVE";
            break;
            case 80: devolucao = "OITENTA";
            break;
            case 81: devolucao = "OITENTA E UM";
            break;
            case 82: devolucao = "OITENTA E DOIS";
            break;
            case 83: devolucao = "OITENTA E TRES";
            break;
            case 84: devolucao = "OITENTA E QUATRO";
            break;
            case 85: devolucao = "OITENTA E CINCO";
            break;
            case 86: devolucao = "OITENTA E SEIS";
            break;
            case 87: devolucao = "OITENTA E SETE";
            break;
            case 88: devolucao = "OITENTA E OITO";
            break;
            case 89: devolucao = "OITENTA E NOVE";
            break;
            case 90: devolucao = "NOVENTA";
            break;
            case 91: devolucao = "NOVENTA E UM";
            break;
            case 92: devolucao = "NOVENTA E DOIS";
            break;
            case 93: devolucao = "NOVENTA E TRES";
            break;
            case 94: devolucao = "NOVENTA E QUATRO";
            break;
            case 95: devolucao = "NOVENTA E CINCO";
            break;
            case 96: devolucao = "NOVENTA E SEIS";
            break;
            case 97: devolucao = "NOVENTA E SETE";
            break;
            case 98: devolucao = "NOVENTA E OITO";
            break;
            case 99: devolucao = "NOVENTA E NOVE";
            break;
            case 100: devolucao = "CEM";
            break;
            case 101: devolucao = "UM";
            break;
            case 102: devolucao = "DOIS";
            break;
            case 103: devolucao = "TRES";
            break;
            case 104: devolucao = "QUATRO";
            break;
            case 105: devolucao = "CINCO";
            break;
            case 106: devolucao = "SEIS";
            break;
            case 107: devolucao = "SETE";
            break;
            case 108: devolucao = "OITO";
            break;
            case 109: devolucao = "NOVE";
            break;
            case 110: devolucao = "DEZ";
            break;
            case 111: devolucao = "ONZE";
            break;
            case 112: devolucao = "DOZE";
            break;
            case 113: devolucao = "TREZE";
            break;
            case 114: devolucao = "QUATORZE";
            break;
            case 115: devolucao = "QUINZE";
            break;
            case 116: devolucao = "DEZESSEIS";
            break;
            case 117: devolucao = "DEZESSETE";
            break;
            case 118: devolucao = "DEZOITO";
            break;
            case 119: devolucao = "DEZENOVE";
            break;
            case 120: devolucao = "VINTE";
            break;
            case 121: devolucao = "VINTE E UM";
            break;
            case 122: devolucao = " VINTE E DOIS";
            break;
            case 123: devolucao = "VINTE E TRES";
            break;
            case 124: devolucao = "VINTE E QUATRO";
            break;
            case 125: devolucao = "VINTE E CINCO";
            break;
            case 126: devolucao = "VINTE E SEIS";
            break;
            case 127: devolucao = "VINTE E SETE";
            break;
            case 128: devolucao = "VINTE E OITO";
            break;
            case 129: devolucao = "VINTE E NOVE";
            break;
            case 130: devolucao = "TRINTA";
            break;
            case 131: devolucao = "TRINTA E UM";
            break;
            case 132: devolucao = "TRINTA E DOIS";
            break;
            case 133: devolucao = "TRINTA E TRES";
            break;
            case 134: devolucao = "TRINTA E QUATRO";
            break;
            case 135: devolucao = "TRINTA E CINCO";
            break;
            case 136: devolucao = "TRINTA E SEIS";
            break;
            default: devolucao = "Invalido";
            break; 
        }
        return devolucao;
    }
    public static void main(String[] args) {
        
    } 
}
/*
Escreva um método que receba como parâmetro um número inteiro, no intervalo de 1 a 999, e
retorne uma String correspondente ao número por extenso. Caso o número esteja fora do
intervalo, o método deve retornar o texto “inválido”.

*/